### ISSUE TITLE
Readme bearbeiten 

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#1]

**Comment by SteffenKonrad** [comment]
Unsere Readme ist noch relativ leer. Nun sollen die wichtigsten Punkte hinzugefügt werden.
-> Projektbeschreibung
-> Namen / GitHub-Benutzernamen
-> Aufgabenstellung vom Projekt

**Comment by nipafx** [comment]
Hey, es geht los. :tada: :smiley:

**Comment by SteffenKonrad** [comment]
Ja, meine beiden Mitstreiter hatten die letzten Tage noch ein paar Probleme mit der Handhabung. Aber jetzt kommt auch was von uns ^^
