### ISSUE TITLE
Erweitern / aktualisieren der Readme

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#17]
:floppy_disk: Erweitern / aktualisieren der Readme um eine Bedienungsanleitung für Benutzer um die Applikation zu benutzen / zu öffnen.

**Comment by nipafx** [comment]
Bei der Gelegenheit könntet ihr die Sprachen festhalten und mit `##` ein paar Überschriften einbauen.

**Comment by H-Hoffmann** [comment]
Wie genau soll ich diese Bedienungsanleitung schreiben? Also wo soll man da anfangen und wie detailliert soll sie sein? Für Benutzer die keine Ahnung von all dem hier haben oder für User von GitHub? Habe die Überschriften eingefügt wie du gesagt hast, danke. Werde morgen früh soweit ich kann alles fertigstellen und dann ne PullRequest machen.
@nicolaiparlog: Die Festlegung der Sprachen hab ich eig schon in der Readme festgehalten. 
 Hast du vlt. auch einen Tipp wie ich Hyperlinks in den Sublime Editor einfügen kann? Meister Google sagt das geht nur mit Plugins...

**Comment by nipafx** [comment]
Die Anleitung kann knapp sein - es reicht den Nutzern zu sagen, dass sie die aktuelle Version [auf der Release Seite](https://github.com/SteffenKonrad/Term_Project_Simulation/releases) herunterladen können. Nur wie der Java-Befehl aussieht, muss man ihnen genau erklären.

:bulb: In Markdown (so heißt diese Art Texte zu formattieren), macht man Links so: `[Text](URL)`, also z.B. `[Wikipedia](https://wikipedia.org)`.

**Comment by SteffenKonrad** [comment]
Kannst du mir grad noch die Anleitung über ein PR schicken. Dann könnte ich schonmal den Release machen & später zur Projektplanung dazu kommen. @H-Hoffmann

**Comment by nipafx** [comment]
Das hier kann geschlossen werden, oder?

**Comment by SteffenKonrad** [comment]
Erweiterung der Readme mit einer Bedienungsanleitung dürfte noch fehlen.

**Comment by nipafx** [comment]
Oops, ja.

**Comment by SteffenKonrad** [comment]
Bedienungsanleitung eingefügt
