### ISSUE TITLE
Integration von Travis

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#18]
:cat: Das HelloWorld-Programm soll in Travis integriert werden. @nicolaiparlog

**Comment by nipafx** [comment]
Da dieses Projekt nicht zu einer Organisation gehört, sondern einem User, kann nur der User Travis aktivieren. 😭 Ich kann das nachher konfigurieren, aber anschmeißen muss es @SteffenKonrad.

Dazu bitte Schritte 2 und 3 aus [dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen. Ich bereite solange schonmal die `.travis.yml` vor.
