### ISSUE TITLE
Veröffentlichung von Version 1.0

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#19]
--> git tag & und anschließende Veröffentlichung 

--> beginn mit Block 2 der Aufgabenstellung

**Comment by nipafx** [comment]
Schritt-für-Schritt-Anleitung für das Release (sobald [der erste Meilentein](https://github.com/SteffenKonrad/Term_Project_Simulation/milestone/1) erledigt ist):

* `master` auschecken
* mit `mvn clean install` und `java-jar target/...jar` sicherstellen, dass alles funktioniert
* in der `pom.xml` bei der Version `-SNAPSHOT` entfernen
* nochmal `mvn clean install` und die JAR aus dem `target`-Ordner (beachte, dass `-SNAPSHOT` fehlt) irgendwohin kopieren
* neuen Commit auf `master` mit der Message "Release version 1.0" (oder so)
* den Commit taggen
* in der `pom.xml` die Version `2.0-SNAPSHOT` eintragen
* neuen Commit auf `master` mit der Message "Start work on 2.0" (oder so)
* alles pushen (mit tags)
* auf GitHub das Releases-Menü finden, aus dem Tag ein Release machen und die JAR anhängen:

![attach-binaries](https://user-images.githubusercontent.com/6537432/28945549-47ed17be-78a7-11e7-8eb0-0b358692fc34.png)

Beachtet, dass es dabei keinen Branch und keinen Pull Request gibt.

**Comment by SteffenKonrad** [comment]
umgesetzt unter Releases Tag: V1.0

**Comment by nipafx** [comment]
Da muss die `...-with-dependencies` dran - die andere lässt sich nicht ausführen.

**Comment by SteffenKonrad** [comment]
Oh sorry, hätte ich vielleicht dazu schreiben sollen. Ist sie hab das dependencies nur händisch gelöscht. (Warum auch immer)

Edit: hab das with-dependencies wieder in die Beschriftung eingefügt

**Comment by nipafx** [comment]
Ach so, damit habe ich nicht gerechnet.  Wäre auch in Ordnung gewesen. :smiley:
