### ISSUE TITLE
Planung einer Programmstruktur / Idee

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#20]
Hier wird vor dem eigentlichen coding über eine grob Programmidee nachgedacht / diskutiert

**Comment by H-Hoffmann** [comment]
Also, ich fang dann mal an...
Für das Erstellen der Verkehrssimulation mit den dutzend Autos und dem Straßennetz: 
- Für die Autos eine Klasse erstellen und für das Straßennetz auch?
- Dem Straßennetz müssten wir dann eine Kapazität geben als festen Referenzwert, wenn es vergleichen will wie viele Autos auf der Straße sind
- dazu registriert und addiert es die Anzahl der Autos auf der Straße und macht dann einen einfachen < als, > als Vergleich
- jedes Auto soll individuell bekannt geben ob es fährt, oder nicht? --> Zufallsentscheidung oder wie soll das geschehen?
- jedes Auto soll sich quasi "merken", ob es fahren kann oder nicht und diese Information dann nachher als print am Ende ausgeben
Soweit so gut? :D

**Comment by nipafx** [comment]
Ja, sehr gut.

> Zufallsentscheidung oder wie soll das geschehen?

Ob ein Auto fahren will oder nicht, soll derjenige entscheiden, der den Konstruktor aufruft (d.h. ein Auto erstellt).

**Comment by H-Hoffmann** [comment]
Vorschlag für die Klasse Car wäre schon mal:
class Car ( val name : String, val drives : Boolean, val capacityCost : Int) {
fun driving () {
     }
}
- val name: Um eine eindeutige, individuelle Zuordnung der Autos zu gewährleisten. Könnte auch mit ner Nummer und Int erfolgen
- val drives: Hier könnte dann hinterlegt werden ob das Auto fahren soll oder nicht durch ein einfach True oder False
- val capacityCost: In Hinblick auf den vierten Block würde ich direkt schon mal eine Eigenschaft für die "Kapazitätskosten" mit einbauen, die bei Autos bei 1 liegen würde. Oder dürfen wir das jetzt noch gar nicht mit einbauen? 
Ist nur ein Vorschlag, was meint ihr?

**Comment by nipafx** [comment]
> In Hinblick auf den vierten Block [...]

Plant lieber nicht so weit voraus. Ihr müsst den Code die ganze Zeit mit euch rumschleppen, obwohl ihr ihn noch nicht braucht.

**Comment by ghost** [comment]
also lieber im nachhinein ergänzen ? 

ja die class car sieht gut aus find ich 
zählen kann man es auch als string oder ? 
wird ja eigentlich immer nur die anzahl der autos addiert subtrahiert wenn ich mich nicht irre

**Comment by nipafx** [comment]
> also lieber im nachhinein ergänzen ?

Ja, erst wenn ihr es wirklich braucht.

**Comment by ghost** [comment]
das merken dann über ne list die wir füllen ? 
zwecks übersicht bietet sich dann eine kleine kapazität an oder ?

**Comment by SteffenKonrad** [comment]
![bildschirmfoto 2017-08-08 um 20 24 54](https://user-images.githubusercontent.com/28274333/29088406-42405b84-7c79-11e7-8abd-fd1f3c270d9a.png)

**Comment by H-Hoffmann** [comment]
Vorschlag für die Struktur: jeweils eine 
- Car.kt, die eine Klasse Cars enthält mit (var name: String, var drives: Boolean)
- RoadNetwork.kt mit einer Klasse Road, die dann (var capacity: Int) enhält
- Main.kt in der dann eben Instanzen aufgerufen werden und die die "fun scenario" enthalten wird und die settings zum Parsen

Dann eben noch die entsprechenden Methoden was ja eig die Herausforderung hier wird....

**Comment by SteffenKonrad** [comment]
Grobe Planung abgeschlossen, weiter Teilplanungen in den dafür vorgesehenen Issues
