### ISSUE TITLE
Dauerhafte Readme Aktualisierung für Aufgaben Block 2

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#21]
Hier soll eine Bedienungsanleitung für das Programm erstellt werden und dem Nutzer in dieser beschrieben werden wie er die Applikation bedien kann.

**Comment by H-Hoffmann** [comment]
Was genau soll dann hier noch neues rein? Also in Bezug auf die Lösung des Blocks zwei.

**Comment by SteffenKonrad** [comment]
Beschreibung editiert --> Bedienungsanleitung fehlt noch @H-Hoffmann

**Comment by H-Hoffmann** [comment]
Also Bedienungsanleitung für Part 2? Werd ich bis zur Deadline Morgen noch schaffen

**Comment by SteffenKonrad** [comment]
In commit 96 umgesetzt
