### ISSUE TITLE
Ordnerstruktur standardisieren

### ISSUE THREAD

**Issue by nipafx** [SteffenKonrad/Term_Project_Simulation#23]
Momentan haben die Sourcen folgende Struktur:

* src
    * HelloWorld (enthält Programmcode)
    * tests (enthält Testcode)

Statt dessen soll die Standardstruktur verwendet werden:

* src
    * main
        * kotlin (enthält Programmcode)
    * test
        * kotlin (enthält Testcode)

Dazu muss auch die POM geändert werden.

Außerdem sollten sich Paketnamen und Ordnerstruktur unterhalb von `kotlin` gleichen, d.h. wenn eine Klasse behauptet im Paket `helloworld` (bitte Kleinbuchstaben für Paketnamen verwenden) zu sein, dann sollte es in `kotlin` einen Ordner `helloworld` geben, der die Klasse enthält.

Bei der Gelegenheit kann auch die Main Class richtig angegeben werden, so dass die JAR erfolgreich startet.

**Comment by nipafx** [comment]
#24 hat dieses Problem zwar angegangen, wurde aber zu früh gemergt. Das Problem zeigt sich am deutlichsten dadurch, dass weder Code noch Tests kompiliert werden, was am Ende zur Folge hat, dass die JAR leer ist. Hier muss also noch was unternommen werden:

* die Pfade für `<sourceDirectory>` und `<testSourceDirectory>` enden in `kotlin`, d.h. _vor_ dem Ordner, der dem obersten Paket entspricht (in diesem Fall `helloworld` bzw. `helloworldtest`)
* die Paketordner müssen kleingeschrieben werden und sollten im `main` und im `test` Baum gleich heißen

**Comment by SteffenKonrad** [comment]
In PR #25 umgesetzt
