### ISSUE TITLE
Erstellen einer "scenario" Funktion

### ISSUE THREAD

**Issue by H-Hoffmann** [SteffenKonrad/Term_Project_Simulation#28]
Diese Funktion soll zum Testen der Simulation dienen und soll mit ca. einem Dutzend Autos getestet werden.

**Comment by H-Hoffmann** [comment]
Die Szenario Funktion dann in der Main.kt mit einbauen nehme ich an? 
Würde dann vorschlagen, dass man einfach als Test eine Liste aus 12 Autos vlt nimmt und durch einen Abgleich der Straßenkapazität festgestellt wird ob die entsprechenden Fahrzeuge ohne Verzögerung fahren oder aber mit einer. Oder wie stellt ihr euch die grob vor?

**Comment by nipafx** [comment]
:+1:

**Comment by SteffenKonrad** [comment]
In PR #38 umgesetzt
