### ISSUE TITLE
Erstellen der ersten Simulation

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#29]
Erzeugen der ersten Programmstruktur in IntelliJ. 
--> ersetzen der HelloWord-Main.kt
--> erstellen einer Car.kt und einer Roadnetwork.kt
--> deren Verknüpfung in der Main.kt

siehe auch Projektplanung: [https://github.com/SteffenKonrad/Term_Project_Simulation/issues/20](url)

**Comment by nipafx** [comment]
Ein Issue sollte erklären worum es geht, _ohne_ dass man dazu ins Olat gucken muss. Sonst ist auch unklar, welche von den Bullet Points ein Issue tatsächlich abdeckt.

**Comment by ghost** [comment]
da das erledigt ist kann das eigentlich geschlossen werden oder ? 
der code befindet sich ja schon in der korrektur bzw wir sind ein issue weiter
