### ISSUE TITLE
Erweiterung um CSV-Eingabe, -Ausgabe

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#31]
Schreibe das Hauptprogramm so um, das Univocity Parsers benutzt wird. Diese Daten einlesen und die resultierenden Daten in eine CSV-Datei schreiben.

:warning: Beachtet werden muss, dass die Szenario-Funktion dabei unangetastet bleiben soll :warning:

**Comment by H-Hoffmann** [comment]
Also dann als erstes mal in der Main.kt die entsprechenden sachen importieren:

```kotlin
import com.univocity.parsers.common.record.Record
import com.univocity.parsers.csv.CsvParser
import com.univocity.parsers.csv.CsvWriter
import com.univocity.parsers.csv.CsvWriterSettings
import com.univocity.parsers.csv.CsvParserSettings
```

Danach dann noch die Setting für das CSV: https://github.com/uniVocity/univocity-parsers#parsers

```kotlin
CsvParserSettings settings = new CsvParserSettings();
//the file used in the example uses '\n' as the line separator sequence.
//the line separator sequence is defined here to ensure systems such as MacOS and Windows
//are able to process this file correctly (MacOS uses '\r'; and Windows uses '\r\n').
settings.getFormat().setLineSeparator("\n");

// creates a CSV parser
CsvParser parser = new CsvParser(settings);

// parses all rows in one go.
List<String[]> allRows = parser.parseAll(getReader("/examples/example.csv"));
```
	
Dann fehlt noch dieser Befehl um die Header nicht mit anzuzeigen, korrekt?

**Comment by nipafx** [comment]
Ja, und die `getReader` Methode gibt es auch noch nicht. Ich hatte dafür eine Klasse `FileAccess` (oder so) erstellt.

**Comment by H-Hoffmann** [comment]
Denke ich habe in meinem letzten PR soweit alles berücksichtigt. Code muss eben noch dahingehend angepasst werden, dass aus den ausgelesen Daten einer CSV auch ne ordentliche Liste erzeugt wird und man im späteren Code damit arbeiten kann. 
@SteffenKonrad , bitte mal den PR checken und falls du denkst dass alles da ist könnte man den issue #31 ja vlt schon schließen. 
Würde dann vlt neue aufmachen, wo die noch fehlenden Bestandteile des Codes beschrieben werden?

**Comment by nipafx** [comment]
Erstmal gucken was bei #35 herauskommt, aber einzelne Details offen zu lassen und dafür neue Issues zu erstellen ist prinzipiell vollkommen in Ordnung.

**Comment by SteffenKonrad** [comment]
umgesetzt in PR #49 umgesetzt
