### ISSUE TITLE
Code-Ordner aufräumen

### ISSUE THREAD

**Issue by nipafx** [SteffenKonrad/Term_Project_Simulation#36]
Der `src` Ordner ist ziemlich durcheinander:

* der Code kompiliert nicht
* der Inhalt von `traffic_simulation.helloworld` wird seid `Main` nicht mehr benötigt
* Klassen und die Dateien, in denen sie enthalten sind, sollen mit Großbuchstaben beginnen
* es gibt keinen Grund für die `2` in `traffic_simulation2`

Bitte geht das bald an, am besten direkt nachdem #35 gelöst ist. (Falls ihr manches schon in dem PR löst, ist das ok, aber versucht nicht alles auf einmal zu machen - das erhöht nur die Fehlerwahrscheinlichkeit.)

**Comment by SteffenKonrad** [comment]
In PR #38 umgesetzt
