### ISSUE TITLE
Tests für die bisher gebauten Funktionen im Programm

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#40]
Hier sollen Tests entwickelt in im Code unter test untergebracht werden. (Beschriftung neuen Test-Klasse mit der jeweiligen Klasse auf die sich der Test bezieht z.B.  Network --> Test-Klasse NetworkTest)

Gleichzeitig werden hier Vorschläge gesammelt was alles getestet werden soll/muss.

**Comment by ghost** [comment]
Ein Test wäre doch ein Auto ins Network zu schicken und vorher und nachher zu vergleichen ob es um 1 in capacity gestiegen ist oder ?

**Comment by ghost** [comment]
Auch eine Kapazität von beispielsweise 0 zu setzen und ein Auto drauf schicken zu wollen müsste eine Testmöglichkeit sein

**Comment by ghost** [comment]
Unsere Car klasse ist nicht testbar kann das sein ? 
zumindest nicht sinnvoll

**Comment by ghost** [comment]
Für die Main mehr autos als bsp 9 was unsere capacity ist einsetzen

**Comment by ghost** [comment]
> Für die Main mehr autos als bsp 9 was unsere capacity ist einsetzen 

behalte die Namen capacity bei oder meint ihr ich soll das ändern ?

**Comment by SteffenKonrad** [comment]
umgesetzt in PR #48
