### ISSUE TITLE
Kosmetik am Code

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#41]
Zu beheben sind kleine Fehler/Verbesserungen die im Code noch nicht gut gelöst sind:

1. Funktion "fun comparison" in "fun enoughCapacity" umwandeln ( Programm nach Veränderung auf Funktion prüfen)

2. Code weiter Kommentieren , sodass alle Funktionen verständlich beschrieben sind 

3. veraltete Kommentare löschen

4. alle Branches entfernen und Verbreitung für Release 2.0

**Comment by H-Hoffmann** [comment]
das code --> reformat hab ich eig bei meiner letzten pull request schon gemacht

**Comment by SteffenKonrad** [comment]
alles klar ist jetzt in der Beschreibung editiert
