### ISSUE TITLE
pom.XML für die CSV vorbereiten

### ISSUE THREAD

**Issue by SteffenKonrad** [SteffenKonrad/Term_Project_Simulation#42]
In der pom wird eine dependency hinzugefügt die das arbeiten mit einer CSV-Datei ermöglicht.

**Comment by H-Hoffmann** [comment]
Hilf mir mal bitte auf die Sprünge, weil ich nciht genau weiß was da noch fehlen soll... Die Univocity Parsers hast du doch schon integriert gehabt

<dependency>
		<groupId>com.univocity</groupId>
		<artifactId>univocity-parsers</artifactId>
		<version>2.5.1</version>
</dependency>

Welche dependency fehlt da noch?

**Comment by SteffenKonrad** [comment]
in PR #38 schon abgehandelt

**Comment by SteffenKonrad** [comment]
Hat H-Hoffmann zu vor geposted: (11.08.17  16:45Uhr)

Hilf mir mal bitte auf die Sprünge, weil ich nciht genau weiß was da noch fehlen soll... Die Univocity Parsers hast du doch schon integriert gehabt

com.univocity univocity-parsers 2.5.1
Welche dependency fehlt da noch?
